import Head from "next/head";
// import styles from "../styles/Home.module.css";

import { createClient } from "next-sanity";
// import { useState } from "react";

const client = createClient({
  projectId: "xk7lf59j",
  dataset: "production",
  apiVersion: "2021-10-21",
  useCdn: false,
});

export default function Home({customers}) {
  // const get_customer = async () => {
  //   try {
  //     const data = await client.fetch(`*[_type == "customer"]`);

  //     console.log(data);

  //     setCustomers(data);
  //   } catch (error) {
  //     console.log(`Error getting data >> ${JSON.stringify(error, false, 2)}`);
  //   }
  // };

  // const [customers, setCustomers] = useState([]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>Customers</h2>
        {customers.length > 0 && (
          <ul>
            {customers.map((customer) => (
              <li key={customer._id}>{customer?.first_name}</li>
            ))}
          </ul>
        )}
        {!customers.length > 0 && <p>No customers to show</p>}
        {customers.length > 0 && (
          <div>
            <pre>{JSON.stringify(customers, null, 2)}</pre>
          </div>
        )}
        {!customers.length > 0 && (
          <div>
            <div>¯\_(ツ)_/¯</div>
            <p>
              Your data will show up here when you've configured everything
              correctly
            </p>
          </div>
        )}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const customers = await client.fetch(`*[_type == "customer"]`);

  return {
    props: {
      customers
    }
  };
}
